ts_data_manager_homepage:
    path:     /
    defaults: { _controller: TSDataManagerBundle:DataManager:DataManager }

ts_data_manager_editrow:
    path:     /editrow/{id}
    defaults: { _controller: TSDataManagerBundle:DataManager:editRow }

ts_register_removerow:
    path:      /removerow/{id}
    defaults: { _controller: TSDataManagerBundle:DataManager:removeRow }

ts_data_manager_save:
    path:     /save/{id}
    defaults: { _controller: TSDataManagerBundle:Import:Save }

ts_data_manager_import:
    path:     /import
    defaults: { _controller: TSDataManagerBundle:Import:Import }

ts_data_manager_curves:
    path:     /curves
    defaults: { _controller: TSDataManagerBundle:Curves:Curves }

ts_data_manager_trend:
    path:     /curves/trend/{e}/{i}/{p}
    defaults: { _controller: TSDataManagerBundle:Curves:trend, e: 1 }
