ts_data_manager_homepage:
    path:     /
    defaults: { _controller: TSDataManagerBundle:DataManager:DataManager }

ts_data_manager_editrow:
    path:     /editrow/{id}
    defaults: { _controller: TSDataManagerBundle:DataManager:editRow }

ts_register_removerow:
    path:      /removerow/{id}
    defaults: { _controller: TSDataManagerBundle:DataManager:removeRow }

ts_data_manager_save:
    path:     /save
    defaults: { _controller: TSDataManagerBundle:DataManager:Save }

ts_data_manager_import:
    path:     /import
    defaults: { _controller: TSDataManagerBundle:DataManager:Import }

ts_data_manager_curves:
    path:     /curves
    defaults: { _controller: TSDataManagerBundle:DataManager:Curves }
