services:
    ts_data_manager.import:
        class: TS\DataManagerBundle\ImportData\ImportData
        arguments:
          - "@phpoffice.spreadsheet"

    ts_data_manager.curves:
        class: TS\DataManagerBundle\Curves\TrendCurves
        arguments:
          - "@ob_highcharts.twig.highcharts_extension"
    