<?php

namespace TS\AssetsBundle\Repository;

/**
 * InverterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InverterRepository extends \Doctrine\ORM\EntityRepository
{
}
