<?php

namespace TS\AssetsBundle\Repository;

/**
 * InverterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InverterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInverters($id) {
        $qb = $this->createQueryBuilder('p');
        return $qb->where('p.substation = :substation')
                ->setParameter('substation', $id)
                ->getQuery()
                ->getArrayResult();
    }

    public function getQueryInverters($id) {
        return $this->createQueryBuilder('p')
                    ->where('p.substation = :substation')
                    ->setParameter('substation', $id);
    }
}
