<?php

namespace TS\AssetsBundle\Repository;

/**
 * SubstationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubstationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSubstations($id) {
        $qb = $this->createQueryBuilder('p');
        return $qb->where('p.site = :site')
                ->setParameter('site', $id)
                ->getQuery()
                ->getArrayResult();
    }
}
