<?php

namespace TS\DataManagerBundle\Repository;

/**
 * ImportDataRawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportDataRawRepository extends \Doctrine\ORM\EntityRepository
{
}
