ts_homepage:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /
    
ts_reports:
    resource: "@TSReportsBundle/Resources/config/routing.yml"
    prefix:   /reports

ts_data_manager:
    resource: "@TSDataManagerBundle/Resources/config/routing.yml"
    prefix:   /datamanager

ts_assets:
    resource: "@TSAssetsBundle/Resources/config/routing.yml"
    prefix:   /assets

ts_register:
    resource: "@TSRegisterBundle/Resources/config/routing.yml"
    prefix:   /register
