ts_assets:
    resource: "@TSAssetsBundle/Resources/config/routing.yml"
    prefix:   /assets

ts_register:
    resource: "@TSRegisterBundle/Resources/config/routing.yml"
    prefix:   /register

app:
    resource: '@AppBundle/Resources/config/routing.yml'