<?php

namespace TS\RegisterBundle\Repository;

/**
 * EnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnsRepository extends \Doctrine\ORM\EntityRepository
{
}
