<?php

namespace TS\RegisterBundle\Repository;

use Doctrine\ORM\QueryBuilder;
/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSelectedEvents($startDate, $endDate, $site)
    {
        $qb = $this->createQueryBuilder('e');
        $qb 
            ->andWhere('e.site = :siteId')
                ->setParameter('siteId',   $site)
            ->andWhere('e.startDate BETWEEN :start AND :end')
                ->setParameter('start', $startDate)
                ->setParameter('end',   $endDate)
            ->orderBy('e.startDate', 'ASC')
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
