services:
    TS\AssetsBundle\Form\SubstationSelectorType:
        arguments: ['@TS\AssetsBundle\Form\DataTransformer\NumberToSubstationTransformer']
        tags: [form.type]

    TS\AssetsBundle\Form\DataTransformer\NumberToSubstationTransformer:
        arguments: ['@doctrine.orm.entity_manager']
        tags: [form.type]
