ts_register_homepage:
    path:     /
    defaults: { _controller: TSRegisterBundle:Register:register }

ts_register_editevent:
    path:     /editevent/{id}
    defaults: { _controller: TSRegisterBundle:Register:editEvent }

ts_register_removeevent:
    path:      /removeevent/{id}
    defaults: { _controller: TSRegisterBundle:Register:removeEvent }

ts_register_listsubstations:
    path:   /listsubstations/{id}
    defaults: { _controller: TSRegisterBundle:Register:listSubstations}

ts_register_listequipments:
    path:   /listequipments/{id}
    defaults: { _controller: TSRegisterBundle:Register:listequipments}

